### ISSUE TITLE
4.3 See which cities a person is looking for roomates in

### ISSUE THREAD

**Issue by NotTimm** [thannansmu/dbui_group3#28]
3

See if the person would be a good match to try to find housing with | Given I have multiple locations listed where I am looking for roomate, when I view another persons profile I should be able to see which cities they are looking. | Given I have listed my location preferences, when I view another person's profile who doesn't match my city preferences, then I should be notified of that in some way

**Comment by kirkwat** [comment]
user can see other user's city in profile
