### ISSUE TITLE
1.6 Require possible roommates to be certain gender

### ISSUE THREAD

**Issue by njbarnard** [thannansmu/dbui_group3#36]
2 | User | Require possible roommates to be certain gender | Not be listed as possible matches for the other gender | Given I am not interested in rooming with a certain gender, when I specify that as a preference I expect that profiles of that gender are unable to view my profile and attempts to reach out are prevented | Given that I don't have a preference in rooming with a certain gender, when I specify that as a preference then I expect to see profiles with either preference

**Comment by kirkwat** [comment]
after reviewing, this feature is already implemented as a search filter on the search page
